apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      id: "0"
  template:
    metadata:
      labels:
        app: zookeeper
        id: "0"
    spec:
      hostname: zoo1
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
