apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
spec:
  type: 
  ports:
    - name: kafka-broker
      port: 9092
      nodePort: 
      targetPort: 
  selector:
    app: kafka-broker
