apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkabroker
  labels:
    app: kafkabroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkabroker
  template:
    metadata:
      labels:
        app: kafkabroker
    spec:
      hostname: kafkabroker
      containers:
      - name: kafkabroker
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-broker:9092"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "<ZOOKEEPER-INTERNAL-IP>:2181"
