apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-nebel
  labels:
    app: mysql-nebel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-nebel
      id: "0"
  template:
    metadata:
      labels:
        app: mysql-nebel
        id: "0"
    spec:
      hostname: localhost
      containers:
      - name: mysql-nebel
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
