apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafkabroker
  name: kafkabroker
  namespace: kafka
spec:
  type: 
  ports:
    - name: kafkabroker
      port: 9092
      nodePort: 
      targetPort: 
  selector:
    app: kafkabroker
