apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-nebel
  name: mysql-nebel
spec:
  type: NodePort
  ports:
    - name: mysql-nebel
      port: 3306
      nodePort: 
      targetPort: 
  selector:
    app: mysql-nebel
